// AUTO-GENERATED by `scripts/codegen-plugin-barrels.ts`. DO NOT EDIT.
// Run `yarn plugins:codegen` after adding/removing/renaming a plugin.

import type { PluginMeta } from "../meta-types";

import { META as accountingMeta } from "../accounting/meta";
import { META as canvasMeta } from "../canvas/meta";
import { META as chartMeta } from "../chart/meta";
import { META as editImagesMeta } from "../editImages/meta";
import { META as encoreDefineEncoreMeta } from "../encore/defineEncoreMeta";
import { META as encoreManageEncoreMeta } from "../encore/manageEncoreMeta";
import { META as generateImageMeta } from "../generateImage/meta";
import { META as manageSkillsMeta } from "../manageSkills/meta";
import { META as manageSourceMeta } from "../manageSource/meta";
import { META as markdownMeta } from "../markdown/meta";
import { META as photoLocationsMeta } from "../photoLocations/meta";
import { META as presentCollectionMeta } from "../presentCollection/meta";
import { META as presentFormMeta } from "../presentForm/meta";
import { META as presentHtmlMeta } from "../presentHtml/meta";
import { META as presentMulmoScriptMeta } from "../presentMulmoScript/meta";
import { META as presentSVGMeta } from "../presentSVG/meta";
import { META as schedulerAutomationsMeta } from "../scheduler/automationsMeta";
import { META as schedulerCalendarMeta } from "../scheduler/calendarMeta";
import { META as spreadsheetMeta } from "../spreadsheet/meta";
import { META as wikiMeta } from "../wiki/meta";

/** All plugin METAs the codegen discovered under `src/plugins/<name>/{meta,*Meta}.ts`.
 *  Combined with `_extras` (if any) inside `src/plugins/metas.ts`. */
export const GENERATED_PLUGIN_METAS = [
  accountingMeta,
  canvasMeta,
  chartMeta,
  editImagesMeta,
  encoreDefineEncoreMeta,
  encoreManageEncoreMeta,
  generateImageMeta,
  manageSkillsMeta,
  manageSourceMeta,
  markdownMeta,
  photoLocationsMeta,
  presentCollectionMeta,
  presentFormMeta,
  presentHtmlMeta,
  presentMulmoScriptMeta,
  presentSVGMeta,
  schedulerAutomationsMeta,
  schedulerCalendarMeta,
  spreadsheetMeta,
  wikiMeta,
] as const satisfies readonly PluginMeta[];

export type GeneratedPluginMetas = typeof GENERATED_PLUGIN_METAS;
