// AUTO-GENERATED by `scripts/codegen-plugin-barrels.ts`. DO NOT EDIT.
// Run `yarn plugins:codegen` after adding/removing/renaming a plugin.

import type { PluginRegistration } from "../../tools/types";

import { REGISTRATION as accountingRegistration } from "../accounting";
import { REGISTRATION as canvasRegistration } from "../canvas";
import { REGISTRATION as chartRegistration } from "../chart";
import { REGISTRATION as editImagesRegistration } from "../editImages";
import { REGISTRATIONS as encoreRegistrations } from "../encore";
import { REGISTRATION as generateImageRegistration } from "../generateImage";
import { REGISTRATION as manageSkillsRegistration } from "../manageSkills";
import { REGISTRATION as manageSourceRegistration } from "../manageSource";
import { REGISTRATION as markdownRegistration } from "../markdown";
import { REGISTRATION as photoLocationsRegistration } from "../photoLocations";
import { REGISTRATION as presentCollectionRegistration } from "../presentCollection";
import { REGISTRATION as presentFormRegistration } from "../presentForm";
import { REGISTRATION as presentHtmlRegistration } from "../presentHtml";
import { REGISTRATION as presentMulmoScriptRegistration } from "../presentMulmoScript";
import { REGISTRATION as presentSVGRegistration } from "../presentSVG";
import { REGISTRATIONS as schedulerRegistrations } from "../scheduler";
import { REGISTRATION as skillRegistration } from "../skill";
import { REGISTRATION as spreadsheetRegistration } from "../spreadsheet";
import { REGISTRATION as textResponseRegistration } from "../textResponse";
import { REGISTRATION as wikiRegistration } from "../wiki";

/** All plugin registrations the codegen discovered under `src/plugins/<name>/index.ts`.
 *  Single-entry plugins export `REGISTRATION`; multi-entry plugins (scheduler)
 *  export `REGISTRATIONS` and are spread. Combined with `_extras` inside
 *  `src/plugins/index.ts`. */
export const GENERATED_PLUGIN_REGISTRATIONS: readonly PluginRegistration[] = [
  accountingRegistration,
  canvasRegistration,
  chartRegistration,
  editImagesRegistration,
  ...encoreRegistrations,
  generateImageRegistration,
  manageSkillsRegistration,
  manageSourceRegistration,
  markdownRegistration,
  photoLocationsRegistration,
  presentCollectionRegistration,
  presentFormRegistration,
  presentHtmlRegistration,
  presentMulmoScriptRegistration,
  presentSVGRegistration,
  ...schedulerRegistrations,
  skillRegistration,
  spreadsheetRegistration,
  textResponseRegistration,
  wikiRegistration,
];
