// AUTO-GENERATED by `scripts/codegen-plugin-barrels.ts`. DO NOT EDIT.
// Run `yarn plugins:codegen` after adding/removing/renaming a plugin.

import type { ServerPluginBinding } from "../server-bindings-types";
import { mcpEndpoint } from "../server-bindings-types";

import accountingDef from "../accounting/definition";
import canvasDef from "../canvas/definition";
import chartDef from "../chart/definition";
import encoreDefineEncoreDef from "../encore/defineEncoreDefinition";
import encoreManageEncoreDef from "../encore/manageEncoreDefinition";
import manageSkillsDef from "../manageSkills/definition";
import manageSourceDef from "../manageSource/definition";
import markdownDef from "../markdown/definition";
import photoLocationsDef from "../photoLocations/definition";
import presentCollectionDef from "../presentCollection/definition";
import presentFormDef from "../presentForm/definition";
import presentHtmlDef from "../presentHtml/definition";
import presentMulmoScriptDef from "../presentMulmoScript/definition";
import presentSVGDef from "../presentSVG/definition";
import schedulerAutomationsDef from "../scheduler/automationsDefinition";
import schedulerCalendarDef from "../scheduler/calendarDefinition";
import spreadsheetDef from "../spreadsheet/definition";
import { META as accountingMeta } from "../accounting/meta";
import { META as canvasMeta } from "../canvas/meta";
import { META as chartMeta } from "../chart/meta";
import { META as encoreManageEncoreMeta } from "../encore/manageEncoreMeta";
import { META as manageSkillsMeta } from "../manageSkills/meta";
import { META as manageSourceMeta } from "../manageSource/meta";
import { META as markdownMeta } from "../markdown/meta";
import { META as photoLocationsMeta } from "../photoLocations/meta";
import { META as presentCollectionMeta } from "../presentCollection/meta";
import { META as presentFormMeta } from "../presentForm/meta";
import { META as presentHtmlMeta } from "../presentHtml/meta";
import { META as presentMulmoScriptMeta } from "../presentMulmoScript/meta";
import { META as presentSVGMeta } from "../presentSVG/meta";
import { META as schedulerCalendarMeta } from "../scheduler/calendarMeta";
import { META as spreadsheetMeta } from "../spreadsheet/meta";

/** All plugin MCP bindings the codegen discovered for plugins whose META declares
 *  both `apiNamespace` and `mcpDispatch`. Plugins without those fields (image plugins,
 *  external npm plugins) live in `_extras.ts`. Combined inside `src/plugins/server.ts`. */
export const GENERATED_SERVER_BINDINGS: readonly ServerPluginBinding[] = [
  { def: accountingDef, endpoint: mcpEndpoint(accountingMeta) },
  { def: canvasDef, endpoint: mcpEndpoint(canvasMeta) },
  { def: chartDef, endpoint: mcpEndpoint(chartMeta) },
  { def: encoreDefineEncoreDef, endpoint: mcpEndpoint(encoreManageEncoreMeta) },
  { def: encoreManageEncoreDef, endpoint: mcpEndpoint(encoreManageEncoreMeta) },
  { def: manageSkillsDef, endpoint: mcpEndpoint(manageSkillsMeta) },
  { def: manageSourceDef, endpoint: mcpEndpoint(manageSourceMeta) },
  { def: markdownDef, endpoint: mcpEndpoint(markdownMeta) },
  { def: photoLocationsDef, endpoint: mcpEndpoint(photoLocationsMeta) },
  { def: presentCollectionDef, endpoint: mcpEndpoint(presentCollectionMeta) },
  { def: presentFormDef, endpoint: mcpEndpoint(presentFormMeta) },
  { def: presentHtmlDef, endpoint: mcpEndpoint(presentHtmlMeta) },
  { def: presentMulmoScriptDef, endpoint: mcpEndpoint(presentMulmoScriptMeta) },
  { def: presentSVGDef, endpoint: mcpEndpoint(presentSVGMeta) },
  { def: schedulerAutomationsDef, endpoint: mcpEndpoint(schedulerCalendarMeta) },
  { def: schedulerCalendarDef, endpoint: mcpEndpoint(schedulerCalendarMeta) },
  { def: spreadsheetDef, endpoint: mcpEndpoint(spreadsheetMeta) },
];
